global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # 1️⃣ Monitoring de Prometheus lui-même
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2️⃣ Monitoring de l'application FINSIG
  - job_name: "finsig-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["finsig-app:8000"]

  # 3️⃣ Monitoring de la base Postgres (via exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["finsig-db:9187"]

  # 4️⃣ Monitoring du système hôte (via node-exporter)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]